---
version: '2'
services: 
  mysql:
    # *-----------------------------*
    # To connect to the DB: 
    #   docker-compose exec mysql bash -c 'mysql -u root -p$MYSQL_ROOT_PASSWORD'
    # *-----------------------------*
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=Admin123
     - MYSQL_USER=connect_user
     - MYSQL_PASSWORD=asgard
    volumes:
     - ./confl/data/mysql:/docker-entrypoint-initdb.d/
     
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./web/nginx
    ports:
      - "3050:80"

  api:
    build:
      dockerfile: Dockerfile
      context: ./web/server
    depends_on:
      - mysql
    volumes:
      - /web/node_modules
      - ./web/server:/web/server

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./web/client
    volumes:
      - /app/node_modules
      - ./web/client:/app
      
  python-scripts:
    build:
      dockerfile: Dockerfile
      context: ./confl/python
    volumes:
      - ./app:/app
      
      


